Travis speed ups
Because the amount of features that the simulator is testing is growing,
the test time is taking a long time. This distributes simulator's tests
over three travis machines to decrease test time.

Add options to defined tests that run one-by-one in a sequential fashion
by defining them in $SINGLE_FEATURES, and allow defining features that
should run together by providing a string of ',' separated list of
multiple tests in $MULTI_FEATURES.

Signed-off-by: Fabio Utzig <utzig@apache.org>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,17 +2,48 @@
 
 language: rust
 
+cache: cargo
+
+matrix:
+  include:
+    # Runs each value defined in $SINGLE_FEATURES by itself in the order
+    # the were defined.
+    - os: linux
+      env: SINGLE_FEATURES="sig-ecdsa enc-kw"
+    - os: linux
+      env: SINGLE_FEATURES="none sig-rsa overwrite-only validate-slot0"
+    - os: linux
+      env: SINGLE_FEATURES="enc-rsa"
+
+    # Values defined in $MULTI_FEATURES consist of any number of features
+    # to be enabled at the same time. The list of multi-values should be
+    # separated by ',' and each list of values is run sequentially in the
+    # defined order.
+    - os: linux
+      env: MULTI_FEATURES="sig-rsa overwrite-only,sig-ecdsa overwrite-only"
+    - os: linux
+      env: MULTI_FEATURES="sig-rsa validate-slot0,sig-ecdsa validate-slot0"
+
+    # FIXME: this test actually fails and must be fixed
+    #- os: linux
+    #  env: MULTI_FEATURES="sig-rsa validate-slot0 overwrite-only"
+
+before_install:
+  - |
+    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+      ./scripts/check-signed-off-by.sh
+      if [ $? -ne 0 ]; then
+        exit 1
+      fi
+    fi
+
+install:
+  - pushd sim
+  - cargo fetch
+  - popd
+
 script:
-  - set -e
-  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then ./scripts/check-signed-off-by.sh; fi
-  - cd sim
-  - cargo test
-  - cargo test --features sig-rsa
-  - cargo test --features sig-ecdsa
-  - cargo test --features overwrite-only
-  - cargo test --features validate-slot0
-  - cargo test --features enc-rsa
-  - cargo test --features enc-kw
+  - ./scripts/run_tests.sh
 
 notifications:
   slack:
